#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
RED='\033[1;31m'
NC='\033[0m'

SYSTEM_TYPE="aarch64-darwin"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

echo "${YELLOW}Updating local flakes...${NC}"
flake_manifest=$(nix flake metadata --json)
local_flakes=$(echo $flake_manifest | jq -r '.locks.nodes | to_entries | map(select(.value.original.type == "path").key)[]')

for flake in $local_flakes; do
  echo "Updating local flake: $flake"
  nix flake update $flake
done
echo "${YELLOW}Finished updating all local flakes.${NC}"

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build .#$FLAKE_SYSTEM $@ --show-trace

echo "${YELLOW}Switching to new generation...${NC}"
./result/sw/bin/darwin-rebuild switch --show-trace --flake .#${SYSTEM_TYPE} $@

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
