name: Build
on:
  - pull_request
  - workflow_dispatch
jobs:
  builds:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 360
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-26.04-arm]
    steps:
      - uses: actions/checkout@v7
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ASAHI_FIRMWARE_DEPLOY_KEY }}
      # - uses: wimpysworld/nothing-but-nix@main
      #   with:
      #     hatchet-protocol: "holster"
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |-
            extra-experimental-features = pipe-operators
      - uses: DeterminateSystems/magic-nix-cache-action@v14
      - uses: cachix/cachix-action@v17
        with:
          name: hackardo
          authToken: "${{ secrets.CACHIX_GITHUB_ACTION_TOKEN }}"
      - name: MacOS Build
        if: matrix.os == 'macos-latest'
        run: nix build .#checks.aarch64-darwin."configurations/darwin/Andrea-MacBook-Air-CI" --print-build-logs
      - name: HomeLab Build
        if: matrix.os == 'ubuntu-26.04-arm'
        run: nix build .#checks.aarch64-linux."configurations/nixos/HomeLab" --print-build-logs
